version: '3'

services:
  cowsay:
    build: ./src/ 

  nginx:
    image: nginx:1.23.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - cowsay